export const styles = {
  app: { minHeight: "100vh", background: "#0d0d0d", color: "#f0ede8", fontFamily: "'Georgia', 'Times New Roman', serif" },
  nav: { position: "sticky", top: 0, zIndex: 100, background: "rgba(13,13,13,0.95)", backdropFilter: "blur(12px)", borderBottom: "1px solid #2a2a2a", padding: "0 2rem" },
  navInner: { maxWidth: 1200, margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", height: 64 },
  logo: { fontSize: "1.2rem", letterSpacing: "0.25em", fontWeight: 700, cursor: "pointer", userSelect: "none" },
  logoAccent: { color: "#d4a843", marginRight: 8 },
  navLinks: { display: "flex", alignItems: "center", gap: "1rem" },
  navBtn: { background: "none", border: "none", color: "#888", fontSize: "0.9rem", cursor: "pointer", letterSpacing: "0.1em", padding: "0.5rem 0.75rem", transition: "color 0.2s" },
  navBtnActive: { color: "#f0ede8" },
  cartBtn: { background: "none", border: "1px solid #3a3a3a", color: "#f0ede8", fontSize: "0.85rem", cursor: "pointer", letterSpacing: "0.12em", padding: "0.5rem 1.2rem", borderRadius: 2, position: "relative", transition: "border-color 0.2s" },
  cartBadge: { position: "absolute", top: -8, right: -8, background: "#d4a843", color: "#000", borderRadius: "50%", width: 18, height: 18, fontSize: "0.7rem", fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "sans-serif" },
  main: { maxWidth: 1200, margin: "0 auto", padding: "0 2rem 4rem" },
  hero: { padding: "5rem 0 3rem", borderBottom: "1px solid #1e1e1e" },
  heroSub: { color: "#d4a843", fontSize: "0.8rem", letterSpacing: "0.3em", textTransform: "uppercase", marginBottom: "1rem" },
  heroTitle: { fontSize: "clamp(2.5rem, 6vw, 4.5rem)", fontWeight: 400, lineHeight: 1.15, marginBottom: "1rem", fontStyle: "normal" },
  heroDesc: { color: "#888", fontSize: "1.05rem", letterSpacing: "0.05em" },
  filterBar: { display: "flex", gap: "0.5rem", flexWrap: "wrap", padding: "2rem 0 1rem" },
  filterBtn: { background: "none", border: "1px solid #2a2a2a", color: "#888", padding: "0.4rem 1rem", borderRadius: 2, cursor: "pointer", fontSize: "0.8rem", letterSpacing: "0.1em", transition: "all 0.2s" },
  filterBtnActive: { borderColor: "#d4a843", color: "#d4a843" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: "1.5rem", paddingTop: "1rem" },
  loadingGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: "1.5rem", paddingTop: "1rem" },
  skeleton: { height: 380, borderRadius: 4, background: "#1a1a1a" },
  card: { background: "#111", border: "1px solid #1e1e1e", borderRadius: 4, overflow: "hidden", transition: "all 0.3s", position: "relative", cursor: "default" },
  cardHovered: { border: "1px solid #3a3a3a", transform: "translateY(-4px)", boxShadow: "0 16px 40px rgba(0,0,0,0.5)" },
  badge: { position: "absolute", top: 12, left: 12, color: "#fff", fontSize: "0.65rem", letterSpacing: "0.12em", fontFamily: "sans-serif", textTransform: "uppercase", padding: "3px 8px", borderRadius: 2, fontWeight: 700, zIndex: 1 },
  cardEmoji: { fontSize: "4rem", textAlign: "center", padding: "2.5rem 1rem 1.5rem", background: "#161616" },
  cardBody: { padding: "1.2rem" },
  cardCategory: { color: "#555", fontSize: "0.7rem", letterSpacing: "0.2em", textTransform: "uppercase", marginBottom: "0.4rem", fontFamily: "sans-serif" },
  cardName: { fontSize: "1.05rem", fontWeight: 500, marginBottom: "0.6rem", lineHeight: 1.3 },
  cardMeta: { display: "flex", justifyContent: "space-between", marginBottom: "1rem", alignItems: "center" },
  cardRating: { color: "#d4a843", fontSize: "0.8rem", fontFamily: "sans-serif" },
  cardReviews: { color: "#555" },
  cardStock: { color: "#555", fontSize: "0.75rem", fontFamily: "sans-serif" },
  cardFooter: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  cardPrice: { fontSize: "1.2rem", fontWeight: 600 },
  addBtn: { background: "#d4a843", color: "#000", border: "none", padding: "0.5rem 1rem", fontSize: "0.75rem", letterSpacing: "0.1em", fontWeight: 700, fontFamily: "sans-serif", cursor: "pointer", borderRadius: 2, transition: "opacity 0.2s" },
  toast: { position: "fixed", bottom: 24, left: "50%", transform: "translateX(-50%)", background: "#d4a843", color: "#000", padding: "0.75rem 1.75rem", borderRadius: 3, fontFamily: "sans-serif", fontWeight: 600, fontSize: "0.85rem", zIndex: 999, boxShadow: "0 8px 24px rgba(0,0,0,0.4)", letterSpacing: "0.05em" },
  pageHeader: { padding: "3rem 0 1.5rem", display: "flex", alignItems: "baseline", gap: "1rem", borderBottom: "1px solid #1e1e1e" },
  pageTitle: { fontSize: "2rem", fontWeight: 400 },
  pageSub: { color: "#555", fontSize: "0.9rem", fontFamily: "sans-serif" },
  empty: { textAlign: "center", padding: "5rem 0" },
  emptyIcon: { fontSize: "3rem", marginBottom: "1rem" },
  emptyText: { color: "#555", marginBottom: "2rem", fontFamily: "sans-serif" },
  cartLayout: { display: "grid", gridTemplateColumns: "1fr 340px", gap: "2rem", paddingTop: "2rem", alignItems: "start" },
  cartItems: { display: "flex", flexDirection: "column", gap: "1rem" },
  cartItem: { display: "flex", alignItems: "center", gap: "1rem", background: "#111", border: "1px solid #1e1e1e", borderRadius: 4, padding: "1rem 1.2rem" },
  cartItemEmoji: { fontSize: "2.2rem", width: 44, textAlign: "center" },
  cartItemInfo: { flex: 1 },
  cartItemName: { fontWeight: 500, marginBottom: "0.2rem" },
  cartItemPrice: { color: "#888", fontSize: "0.85rem", fontFamily: "sans-serif" },
  qtyControl: { display: "flex", alignItems: "center", gap: "0.5rem", background: "#0d0d0d", border: "1px solid #2a2a2a", borderRadius: 2, padding: "0.2rem 0.5rem" },
  qtyBtn: { background: "none", border: "none", color: "#f0ede8", cursor: "pointer", fontSize: "1rem", lineHeight: 1, padding: "0 4px" },
  qtyNum: { minWidth: 20, textAlign: "center", fontFamily: "sans-serif", fontSize: "0.9rem" },
  cartItemTotal: { minWidth: 60, textAlign: "right", fontWeight: 600, fontFamily: "sans-serif" },
  removeBtn: { background: "none", border: "none", color: "#444", cursor: "pointer", fontSize: "0.8rem", padding: "4px 6px", transition: "color 0.2s" },
  cartSummary: { background: "#111", border: "1px solid #1e1e1e", borderRadius: 4, padding: "1.5rem", position: "sticky", top: 80 },
  summaryTitle: { fontWeight: 500, marginBottom: "1.5rem", fontSize: "1.1rem" },
  summaryRow: { display: "flex", justifyContent: "space-between", marginBottom: "0.8rem", color: "#888", fontFamily: "sans-serif", fontSize: "0.9rem" },
  summaryTotal: { color: "#f0ede8", fontWeight: 600, fontSize: "1rem", borderTop: "1px solid #2a2a2a", paddingTop: "0.8rem", marginTop: "0.4rem" },
  primaryBtn: { display: "block", width: "100%", background: "#d4a843", color: "#000", border: "none", padding: "0.9rem 1.5rem", fontWeight: 700, fontFamily: "sans-serif", fontSize: "0.85rem", letterSpacing: "0.1em", cursor: "pointer", borderRadius: 2, marginTop: "1.5rem", transition: "opacity 0.2s" },
  ghostBtn: { display: "block", width: "100%", background: "none", color: "#555", border: "none", padding: "0.8rem", fontFamily: "sans-serif", fontSize: "0.8rem", cursor: "pointer", marginTop: "0.5rem", letterSpacing: "0.08em" },
  checkoutLayout: { display: "grid", gridTemplateColumns: "1fr 360px", gap: "2rem", paddingTop: "2rem", alignItems: "start" },
  checkoutForm: { background: "#111", border: "1px solid #1e1e1e", borderRadius: 4, padding: "2rem" },
  formSection: { fontSize: "1rem", fontWeight: 500, letterSpacing: "0.1em", marginBottom: "1.2rem", color: "#d4a843", display: "flex", alignItems: "center", gap: "0.75rem" },
  demoBadge: { background: "#222", color: "#888", fontSize: "0.65rem", fontFamily: "sans-serif", padding: "2px 8px", borderRadius: 10, letterSpacing: "0.1em" },
  inputGroup: { marginBottom: "1rem" },
  inputLabel: { display: "block", color: "#888", fontSize: "0.75rem", letterSpacing: "0.1em", fontFamily: "sans-serif", marginBottom: "0.4rem" },
  input: { width: "100%", background: "#0d0d0d", border: "1px solid #2a2a2a", color: "#f0ede8", padding: "0.75rem 1rem", borderRadius: 2, fontFamily: "Georgia, serif", fontSize: "0.95rem", boxSizing: "border-box", outline: "none" },
  demoCard: { background: "#0d0d0d", border: "1px solid #2a2a2a", borderRadius: 4, padding: "1rem 1.2rem", fontSize: "0.85rem", fontFamily: "sans-serif", color: "#555" },
  demoCardRow: { display: "flex", gap: "1.5rem", marginBottom: "0.4rem", alignItems: "center", flexWrap: "wrap" },
  orderReview: { background: "#111", border: "1px solid #1e1e1e", borderRadius: 4, padding: "1.5rem", position: "sticky", top: 80 },
  reviewItem: { display: "flex", alignItems: "center", gap: "0.75rem", paddingBottom: "0.75rem", borderBottom: "1px solid #1a1a1a", marginBottom: "0.75rem", fontFamily: "sans-serif" },
  reviewTotal: { display: "flex", justifyContent: "space-between", fontWeight: 700, fontSize: "1.05rem", paddingTop: "0.5rem" },
  confirmBox: { maxWidth: 480, margin: "0 auto", background: "#111", border: "1px solid #1e1e1e", borderRadius: 4, padding: "3rem 2.5rem" },
  confirmIcon: { width: 60, height: 60, borderRadius: "50%", background: "#d4a843", color: "#000", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.6rem", fontWeight: 700, margin: "0 auto 1.5rem", fontFamily: "sans-serif" },
  confirmTitle: { fontSize: "1.8rem", fontWeight: 400, marginBottom: "0.5rem" },
  confirmSub: { color: "#888", fontFamily: "sans-serif", marginBottom: "2rem" },
  confirmDetails: { background: "#0d0d0d", borderRadius: 4, padding: "1.2rem", textAlign: "left" },
  confirmRow: { display: "flex", justifyContent: "space-between", padding: "0.5rem 0", borderBottom: "1px solid #1a1a1a", fontFamily: "sans-serif", fontSize: "0.85rem", color: "#888" },
};

export const globalStyles = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #0d0d0d; }
  .skeleton { animation: pulse 1.5s ease-in-out infinite; }
  @keyframes pulse { 0%,100% { opacity: 0.5; } 50% { opacity: 1; } }
  button:hover { opacity: 0.85; }
  input:focus { border-color: #d4a843 !important; }
  ::-webkit-scrollbar { width: 6px; }
  ::-webkit-scrollbar-track { background: #0d0d0d; }
  ::-webkit-scrollbar-thumb { background: #2a2a2a; border-radius: 3px; }
`;
